
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_MCUX_COMPONENT_driver.cmsis_lpi2c=y
CONFIG_MCUX_COMPONENT_driver.dma=y
CONFIG_MCUX_COMPONENT_driver.dmamux=y
CONFIG_MCUX_COMPONENT_driver.edma=y
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.lpi2c_edma=y

CONFIG_MCUX_COMPONENT_component.lists=y
CONFIG_MCUX_COMPONENT_utility.assert=y
CONFIG_MCUX_COMPONENT_utility.debug_console_template_config=y
CONFIG_MCUX_COMPONENT_component.gpio_adapter=y