CONFIG_MCUX_PRJSEG_module.board.suite=y
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=y
CONFIG_MCUX_COMPONENT_driver.flash_config=y
CONFIG_MCUX_COMPONENT_driver.clock=y
CONFIG_MCUX_COMPONENT_driver.i2s_bridge=y
CONFIG_MCUX_COMPONENT_driver.inputmux_connections=y
CONFIG_MCUX_COMPONENT_driver.io_mux=y
CONFIG_MCUX_COMPONENT_driver.iped_rw61x=y
CONFIG_MCUX_COMPONENT_driver.memory=y
CONFIG_MCUX_COMPONENT_driver.ocotp_rw61x=y
CONFIG_MCUX_COMPONENT_driver.power=y
CONFIG_MCUX_COMPONENT_driver.reset=y
CONFIG_MCUX_COMPONENT_CMSIS_Driver_Include.I2C=y
CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_COMPONENT_device.system=y
CONFIG_MCUX_COMPONENT_device.startup=y
CONFIG_MCUX_COMPONENT_device.RTE=y
CONFIG_MCUX_COMPONENT_driver.cache_cache64=y
CONFIG_MCUX_COMPONENT_driver.common=y
CONFIG_MCUX_COMPONENT_driver.flexcomm=y
CONFIG_MCUX_COMPONENT_driver.flexcomm_usart=y
CONFIG_MCUX_COMPONENT_driver.flexcomm_i2c_dma=y
CONFIG_MCUX_COMPONENT_driver.flexcomm_i2c=y
CONFIG_MCUX_COMPONENT_driver.flexspi=y
CONFIG_MCUX_COMPONENT_driver.inputmux=y
CONFIG_MCUX_COMPONENT_driver.lpc_dma=y
CONFIG_MCUX_COMPONENT_driver.lpc_gpio=y
CONFIG_MCUX_COMPONENT_driver.cmsis_flexcomm_i2c=y
CONFIG_MCUX_COMPONENT_utility.assert_lite=y
CONFIG_MCUX_COMPONENT_utilities.misc_utilities=y
CONFIG_MCUX_COMPONENT_utility.str=y
CONFIG_MCUX_COMPONENT_utility.debug_console_lite=y
CONFIG_MCUX_COMPONENT_component.usart_adapter=y
CONFIG_MCUX_COMPONENT_component.els_pkc.buffer=y
CONFIG_MCUX_COMPONENT_component.els_pkc.core=y
CONFIG_MCUX_COMPONENT_component.els_pkc.els_header_only=y
CONFIG_MCUX_COMPONENT_component.els_pkc.els_common=y
CONFIG_MCUX_COMPONENT_component.els_pkc.standalone_gdet=y
CONFIG_MCUX_COMPONENT_component.els_pkc.memory=y
CONFIG_MCUX_COMPONENT_component.els_pkc.pre_processor=y
CONFIG_MCUX_COMPONENT_component.els_pkc.data_integrity=y
CONFIG_MCUX_COMPONENT_component.els_pkc.flow_protection=y
CONFIG_MCUX_COMPONENT_component.els_pkc.param_integrity=y
CONFIG_MCUX_COMPONENT_component.els_pkc.secure_counter=y
CONFIG_MCUX_COMPONENT_component.els_pkc.toolchain=y
CONFIG_MCUX_COMPONENT_component.els_pkc.platform.rw61x_inf_header_only=y
CONFIG_MCUX_COMPONENT_component.els_pkc.platform.rw61x_standalone_clib_gdet_sensor=y
CONFIG_MCUX_PRJSEG_module.board.wireless.app_services=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.clock=n
CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.display_support=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.console_lite=n