
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_MCUX_COMPONENT_driver.cmsis_flexcomm_i2c=y
CONFIG_MCUX_COMPONENT_driver.flexcomm_i2c=y
CONFIG_MCUX_COMPONENT_driver.flexcomm_i2c_dma=y
CONFIG_MCUX_COMPONENT_driver.lpc_dma=y

CONFIG_MCUX_COMPONENT_component.lists=y
CONFIG_MCUX_COMPONENT_utility.assert=y
CONFIG_MCUX_COMPONENT_utility.debug_console_template_config=y
CONFIG_MCUX_COMPONENT_component.lpc_gpio_adapter=y
CONFIG_MCUX_COMPONENT_driver.flash_config=y

